### ISSUE TITLE
Failed to login on JetBrains Aqua

### ISSUE THREAD

**Issue by Can-Kizilay** [MicroFocus/octane-intellij-plugin#136]
I'm having trouble logging in to the JetBrains Aqua plugin as the **/api/current_user** is showing null. It appears that the IDE is unable to retrieve the cookies from the default browser.

**Comment by pikachugb** [comment]
Hi! Thanks for reaching us.
Unfortunately, our plugin was designed only for Intellij. It is not developed, supported and tested for any other Jetbrains IDEs.
