### ISSUE TITLE
Pull/refresh feature files in IntelliJ

### ISSUE THREAD

**Issue by panama69** [MicroFocus/octane-intellij-plugin#7]
Right now once you download a feature file from Octane in to the Cucumber test project there is no way to pull and merge any changes that were made in Octane.

It would be great if an automation engineer would be able to select one or more *.feature files and have a refresh option.  This would re-pull the feature file from Octane and merge it with the feature file in the IntelliJ project.

**Comment by atothhpe** [comment]
What exactly does merge mean, Is it a simple overwrite of the file, basically it would download the newest version from octane and overwrite it. Or is it expected that the file would somehow stay in sync with Octane. That changes can be made to the file in both IntelliJ and Octane and they would get merged into one. The first option where the file can only be edited in Octane and the refresh is just an overwrite is a lot easier from a technical point of view.

**Comment by panama69** [comment]
merge here would be similar to what happens when you perform a "git pull" and the origin has changed from your local copy.  it merges the changes into one file and you need to determine what changes to keep or modify.

**Comment by atothhpe** [comment]
That can be quite a pain to implement.
Does it also include saving the file? If the changes are merged, should this update the file on Octane? Like a git commit/push? Guessing yes, because otherwise the merge is not that useful.
